// Runs the GPU spec (harmony.webgl.test.ts) through a SafeLight checkout's
// WebGL test harness — headless Chromium on SwiftShader, the real renderer,
// the real prepass framework — so the stages are verified where the CPU
// suite cannot see: shader compilation with the host's namespacing, the
// prepass idle gate and unit allocation, half-float targets, and the actual
// per-draw cost.
//
// The spec is copied into the checkout for the run (its harness helpers and
// path aliases only resolve from inside) and removed again afterwards, along
// with the generated config. Point SAFELIGHT_CORE at the checkout; by default
// a `SafeLight` directory beside this repository or beside its parent folder
// is used.
"use strict";

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const extension = path.resolve(__dirname, "..", "..");
const isCheckout = (dir) => fs.existsSync(path.join(dir, "vitest.webgl.config.ts"));
const candidates = process.env.SAFELIGHT_CORE
  ? [path.resolve(process.env.SAFELIGHT_CORE)]
  : [path.join(extension, "..", "SafeLight"), path.join(extension, "..", "..", "SafeLight")];
const core = candidates.find(isCheckout);
if (!core) {
  console.error(`No SafeLight checkout found (tried ${candidates.join(", ")}); set SAFELIGHT_CORE`);
  process.exit(2);
}

const specDir = path.join(core, "src", "rendering", "webgl", "__ch_gpu__");
const specFile = path.join(specDir, "harmony.webgl.test.ts");
const configFile = path.join(core, "vitest.ch-gpu.config.ts");

const config = `/// <reference types="vitest/config" />
// Generated by the Colour Harmony extension's test/gpu/run.cjs — removed
// after the run. Same rig as vitest.webgl.config.ts, plus the extension's
// sources and its copied spec.
import path from "path";
import { readFileSync } from "fs";
import { defineConfig } from "vite";
import { playwright } from "@vitest/browser-playwright";

const pkg = JSON.parse(readFileSync(path.resolve(__dirname, "package.json"), "utf-8")) as { version: string };
const EXT = ${JSON.stringify(extension)};

export default defineConfig({
  cacheDir: "node_modules/.vite-cache-ch-gpu",
  define: { __APP_VERSION__: JSON.stringify(pkg.version) },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      "libraw-wasm": path.resolve(__dirname, "src/raw/vendor/libraw-wasm/index.js"),
      "@ch": path.join(EXT, "src"),
      "@ch-test": path.join(EXT, "test"),
    },
  },
  server: { fs: { allow: [__dirname, EXT] } },
  optimizeDeps: { exclude: ["libraw-wasm"] },
  test: {
    name: "ch-gpu",
    include: ["src/rendering/webgl/__ch_gpu__/*.webgl.test.ts"],
    testTimeout: 300_000,
    browser: {
      enabled: true,
      headless: true,
      provider: playwright(),
      instances: [
        {
          browser: "chromium",
          launch: { args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] },
        },
      ],
    },
  },
});
`;

let status = 1;
try {
  fs.mkdirSync(specDir, { recursive: true });
  fs.copyFileSync(path.join(__dirname, "harmony.webgl.test.ts"), specFile);
  fs.writeFileSync(configFile, config);
  const result = spawnSync("npx", ["vitest", "run", "--config", path.basename(configFile), "--reporter=verbose"], {
    cwd: core,
    stdio: "inherit",
    shell: true,
  });
  status = result.status ?? 1;
} finally {
  fs.rmSync(specDir, { recursive: true, force: true });
  fs.rmSync(configFile, { force: true });
}
process.exit(status);
